-- DEFAULT
-- require "user.options"
-- require "user.keymaps"
-- require "user.plugins"
-- require "user.colorscheme"
-- require "user.cmp"
require "user.lsp"
-- require "user.telescope"
-- require "user.treesitter"
require "user.autopairs"
-- require "user.comment"
-- require "user.nvim-tree"
require "user.gitsigns"
-- require "user.bufferline"
require "user.lualine"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
require "user.indentline"
-- require "user.alpha"
-- require "user.whichkey"
-- require "user.autocommands"

-- MARWEN
require "marwen.plugins"
require "marwen.options"
require "marwen.nvim-tree"
require "marwen.colorscheme"
require "marwen.keymaps"
require "marwen.bufferline"
require "marwen.tmux"
require "marwen.neoscroll"
require "marwen.telescope"
require "marwen.treesitter"
require "marwen.cmp"
require "marwen.comment"
